<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/client.php");
	include("$currDir/client_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('client');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "client";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`client`.`id_client`" => "id_client",
		"`client`.`nom_du_client`" => "nom_du_client",
		"`client`.`nom_du_contact`" => "nom_du_contact",
		"`client`.`titre_du_contact`" => "titre_du_contact",
		"`client`.`adresse_postale`" => "adresse_postale",
		"`client`.`ville`" => "ville",
		"if(CHAR_LENGTH(`client`.`code_postal`)>5, concat(left(`client`.`code_postal`,5),' ...'), `client`.`code_postal`)" => "code_postal",
		"`client`.`adresse_gm`" => "adresse_gm",
		"`client`.`pays`" => "pays",
		"`client`.`telephone_contact`" => "telephone_contact",
		"`client`.`email`" => "email",
		"`client`.`commentaires`" => "commentaires"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`client`.`id_client`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`client`.`id_client`" => "id_client",
		"`client`.`nom_du_client`" => "nom_du_client",
		"`client`.`nom_du_contact`" => "nom_du_contact",
		"`client`.`titre_du_contact`" => "titre_du_contact",
		"`client`.`adresse_postale`" => "adresse_postale",
		"`client`.`ville`" => "ville",
		"`client`.`code_postal`" => "code_postal",
		"`client`.`adresse_gm`" => "adresse_gm",
		"`client`.`pays`" => "pays",
		"`client`.`telephone_contact`" => "telephone_contact",
		"`client`.`email`" => "email",
		"`client`.`commentaires`" => "commentaires"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`client`.`id_client`" => "Id client",
		"`client`.`nom_du_client`" => "Nom du client",
		"`client`.`nom_du_contact`" => "Nom du contact",
		"`client`.`titre_du_contact`" => "Titre du contact",
		"`client`.`adresse_postale`" => "Adresse postale",
		"`client`.`ville`" => "Ville",
		"`client`.`code_postal`" => "Code postal",
		"`client`.`adresse_gm`" => "Adresse GoogleMap",
		"`client`.`pays`" => "Pays",
		"`client`.`telephone_contact`" => "Telephone contact",
		"`client`.`email`" => "Email",
		"`client`.`commentaires`" => "Commentaires"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`client`.`id_client`" => "id_client",
		"`client`.`nom_du_client`" => "nom_du_client",
		"`client`.`nom_du_contact`" => "nom_du_contact",
		"`client`.`titre_du_contact`" => "titre_du_contact",
		"`client`.`adresse_postale`" => "adresse_postale",
		"`client`.`ville`" => "ville",
		"`client`.`code_postal`" => "Code postal",
		"`client`.`adresse_gm`" => "adresse_gm",
		"`client`.`pays`" => "pays",
		"`client`.`telephone_contact`" => "telephone_contact",
		"`client`.`email`" => "email",
		"`client`.`commentaires`" => "commentaires"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`client` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "client_view.php";
	$x->RedirectAfterInsert = "client_view.php?SelectedID=#ID#";
	$x->TableTitle = "Client";
	$x->TableIcon = "resources/table_icons/account_balances.png";
	$x->PrimaryKey = "`client`.`id_client`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Nom du client", "Nom du contact", "Titre du contact", "Adresse postale", "Ville", "Code postal", "Adresse GoogleMap", "Pays", "Telephone contact", "Email");
	$x->ColFieldName = array('nom_du_client', 'nom_du_contact', 'titre_du_contact', 'adresse_postale', 'ville', 'code_postal', 'adresse_gm', 'pays', 'telephone_contact', 'email');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11);

	// template paths below are based on the app main directory
	$x->Template = 'templates/client_templateTV.html';
	$x->SelectedTemplate = 'templates/client_templateTVS.html';
	$x->TemplateDV = 'templates/client_templateDV.html';
	$x->TemplateDVP = 'templates/client_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `client`.`id_client`=membership_userrecords.pkValue and membership_userrecords.tableName='client' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `client`.`id_client`=membership_userrecords.pkValue and membership_userrecords.tableName='client' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`client`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: client_init
	$render=TRUE;
	if(function_exists('client_init')){
		$args=array();
		$render=client_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: client_header
	$headerCode='';
	if(function_exists('client_header')){
		$args=array();
		$headerCode=client_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: client_footer
	$footerCode='';
	if(function_exists('client_footer')){
		$args=array();
		$footerCode=client_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>