<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/consultant.php");
	include("$currDir/consultant_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('consultant');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "consultant";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`consultant`.`id_consultant`" => "id_consultant",
		"`consultant`.`Matricule`" => "Matricule",
		"`consultant`.`Prenom`" => "Prenom",
		"`consultant`.`Nom`" => "Nom",
		"`consultant`.`email`" => "email",
		"`consultant`.`adresse_postale`" => "adresse_postale",
		"`consultant`.`saisie_par`" => "saisie_par",
		"IF(    CHAR_LENGTH(`consultant1`.`Prenom`) || CHAR_LENGTH(`consultant1`.`Nom`), CONCAT_WS('',   `consultant1`.`Prenom`, ', ', `consultant1`.`Nom`), '') /* Coache par */" => "coache_par",
		"IF(    CHAR_LENGTH(`emploi_fonctionnel1`.`titre_emploifct`), CONCAT_WS('',   `emploi_fonctionnel1`.`titre_emploifct`), '') /* Emploi fonctionnel */" => "emploi_fonctionnel"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`consultant`.`id_consultant`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`emploi_fonctionnel1`.`titre_emploifct`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`consultant`.`id_consultant`" => "id_consultant",
		"`consultant`.`Matricule`" => "Matricule",
		"`consultant`.`Prenom`" => "Prenom",
		"`consultant`.`Nom`" => "Nom",
		"`consultant`.`email`" => "email",
		"`consultant`.`adresse_postale`" => "adresse_postale",
		"`consultant`.`saisie_par`" => "saisie_par",
		"IF(    CHAR_LENGTH(`consultant1`.`Prenom`) || CHAR_LENGTH(`consultant1`.`Nom`), CONCAT_WS('',   `consultant1`.`Prenom`, ', ', `consultant1`.`Nom`), '') /* Coache par */" => "coache_par",
		"IF(    CHAR_LENGTH(`emploi_fonctionnel1`.`titre_emploifct`), CONCAT_WS('',   `emploi_fonctionnel1`.`titre_emploifct`), '') /* Emploi fonctionnel */" => "emploi_fonctionnel"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`consultant`.`id_consultant`" => "Id consultant",
		"`consultant`.`Matricule`" => "Matricule",
		"`consultant`.`Prenom`" => "Prenom",
		"`consultant`.`Nom`" => "Nom",
		"`consultant`.`email`" => "Email",
		"`consultant`.`adresse_postale`" => "Adresse postale",
		"`consultant`.`saisie_par`" => "Saisie par",
		"IF(    CHAR_LENGTH(`consultant1`.`Prenom`) || CHAR_LENGTH(`consultant1`.`Nom`), CONCAT_WS('',   `consultant1`.`Prenom`, ', ', `consultant1`.`Nom`), '') /* Coache par */" => "Coache par",
		"IF(    CHAR_LENGTH(`emploi_fonctionnel1`.`titre_emploifct`), CONCAT_WS('',   `emploi_fonctionnel1`.`titre_emploifct`), '') /* Emploi fonctionnel */" => "Emploi fonctionnel"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`consultant`.`id_consultant`" => "id_consultant",
		"`consultant`.`Matricule`" => "Matricule",
		"`consultant`.`Prenom`" => "Prenom",
		"`consultant`.`Nom`" => "Nom",
		"`consultant`.`email`" => "email",
		"`consultant`.`adresse_postale`" => "adresse_postale",
		"`consultant`.`saisie_par`" => "saisie_par",
		"IF(    CHAR_LENGTH(`consultant1`.`Prenom`) || CHAR_LENGTH(`consultant1`.`Nom`), CONCAT_WS('',   `consultant1`.`Prenom`, ', ', `consultant1`.`Nom`), '') /* Coache par */" => "coache_par",
		"IF(    CHAR_LENGTH(`emploi_fonctionnel1`.`titre_emploifct`), CONCAT_WS('',   `emploi_fonctionnel1`.`titre_emploifct`), '') /* Emploi fonctionnel */" => "emploi_fonctionnel"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'coache_par' => 'Coache par', 'emploi_fonctionnel' => 'Emploi fonctionnel');

	$x->QueryFrom = "`consultant` LEFT JOIN `consultant` as consultant1 ON `consultant1`.`id_consultant`=`consultant`.`coache_par` LEFT JOIN `emploi_fonctionnel` as emploi_fonctionnel1 ON `emploi_fonctionnel1`.`id_ef`=`consultant`.`emploi_fonctionnel` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "consultant_view.php";
	$x->RedirectAfterInsert = "consultant_view.php?SelectedID=#ID#";
	$x->TableTitle = "Consultant";
	$x->TableIcon = "resources/table_icons/administrator.png";
	$x->PrimaryKey = "`consultant`.`id_consultant`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("Matricule", "Prenom", "Nom", "Email", "Emploi fonctionnel");
	$x->ColFieldName = array('Matricule', 'Prenom', 'Nom', 'email', 'emploi_fonctionnel');
	$x->ColNumber  = array(2, 3, 4, 5, 9);

	// template paths below are based on the app main directory
	$x->Template = 'templates/consultant_templateTV.html';
	$x->SelectedTemplate = 'templates/consultant_templateTVS.html';
	$x->TemplateDV = 'templates/consultant_templateDV.html';
	$x->TemplateDVP = 'templates/consultant_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "col-md-offset-2 col-md-8";
	$x->DVClasses = "col-md-offset-2 col-md-8";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `consultant`.`id_consultant`=membership_userrecords.pkValue and membership_userrecords.tableName='consultant' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `consultant`.`id_consultant`=membership_userrecords.pkValue and membership_userrecords.tableName='consultant' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`consultant`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: consultant_init
	$render=TRUE;
	if(function_exists('consultant_init')){
		$args=array();
		$render=consultant_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: consultant_header
	$headerCode='';
	if(function_exists('consultant_header')){
		$args=array();
		$headerCode=consultant_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: consultant_footer
	$footerCode='';
	if(function_exists('consultant_footer')){
		$args=array();
		$footerCode=consultant_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>