<?php
// This script and data application were generated by AppGini 5.81
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/domaine.php");
	include("$currDir/domaine_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('domaine');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "domaine";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`domaine`.`id_domaine`" => "id_domaine",
		"`domaine`.`titre_domaine`" => "titre_domaine",
		"`domaine`.`description`" => "description",
		"IF(    CHAR_LENGTH(`filiere1`.`titre_filiere`), CONCAT_WS('',   `filiere1`.`titre_filiere`), '') /* Rattache a la Fili&#232;re */" => "rattache_a_filiere",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`domaine`.`id_domaine`',
		2 => 2,
		3 => 3,
		4 => '`filiere1`.`titre_filiere`',
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`domaine`.`id_domaine`" => "id_domaine",
		"`domaine`.`titre_domaine`" => "titre_domaine",
		"`domaine`.`description`" => "description",
		"IF(    CHAR_LENGTH(`filiere1`.`titre_filiere`), CONCAT_WS('',   `filiere1`.`titre_filiere`), '') /* Rattache a la Fili&#232;re */" => "rattache_a_filiere",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`domaine`.`id_domaine`" => "Id domaine",
		"`domaine`.`titre_domaine`" => "Titre domaine",
		"`domaine`.`description`" => "Description",
		"IF(    CHAR_LENGTH(`filiere1`.`titre_filiere`), CONCAT_WS('',   `filiere1`.`titre_filiere`), '') /* Rattache a la Fili&#232;re */" => "Rattache a la Fili&#232;re",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`domaine`.`id_domaine`" => "id_domaine",
		"`domaine`.`titre_domaine`" => "titre_domaine",
		"`domaine`.`description`" => "description",
		"IF(    CHAR_LENGTH(`filiere1`.`titre_filiere`), CONCAT_WS('',   `filiere1`.`titre_filiere`), '') /* Rattache a la Fili&#232;re */" => "rattache_a_filiere",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('rattache_a_filiere' => 'Rattache a la Fili&#232;re', );

	$x->QueryFrom = "`domaine` LEFT JOIN `filiere` as filiere1 ON `filiere1`.`id_filiere`=`domaine`.`rattache_a_filiere` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "domaine_view.php";
	$x->RedirectAfterInsert = "domaine_view.php?SelectedID=#ID#";
	$x->TableTitle = "Domaine";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`domaine`.`id_domaine`";

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Titre domaine", "Description", "Rattache a la Fili&#232;re");
	$x->ColFieldName = array('titre_domaine', 'description', 'rattache_a_filiere');
	$x->ColNumber  = array(2, 3, 4);

	// template paths below are based on the app main directory
	$x->Template = 'templates/domaine_templateTV.html';
	$x->SelectedTemplate = 'templates/domaine_templateTVS.html';
	$x->TemplateDV = 'templates/domaine_templateDV.html';
	$x->TemplateDVP = 'templates/domaine_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `domaine`.`id_domaine`=membership_userrecords.pkValue and membership_userrecords.tableName='domaine' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `domaine`.`id_domaine`=membership_userrecords.pkValue and membership_userrecords.tableName='domaine' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`domaine`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: domaine_init
	$render=TRUE;
	if(function_exists('domaine_init')) {
		$args=array();
		$render=domaine_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: domaine_header
	$headerCode='';
	if(function_exists('domaine_header')) {
		$args=array();
		$headerCode=domaine_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: domaine_footer
	$footerCode='';
	if(function_exists('domaine_footer')) {
		$args=array();
		$footerCode=domaine_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>