<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/formation_suivi.php");
	include("$currDir/formation_suivi_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('formation_suivi');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "formation_suivi";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`formation_suivi`.`id`" => "id",
		"`formation_suivi`.`titre`" => "titre",
		"`formation_suivi`.`niveau`" => "niveau",
		"if(`formation_suivi`.`date_deb`,date_format(`formation_suivi`.`date_deb`,'%d/%m/%Y'),'')" => "date_deb",
		"if(`formation_suivi`.`date_fin`,date_format(`formation_suivi`.`date_fin`,'%d/%m/%Y'),'')" => "date_fin",
		"IF(    CHAR_LENGTH(`competences_ref1`.`titre_competence`) || CHAR_LENGTH(`domaine2`.`titre_domaine`) || CHAR_LENGTH(`filiere2`.`titre_filiere`), CONCAT_WS('',   `competences_ref1`.`titre_competence`, ' ', `domaine2`.`titre_domaine`, '>', `filiere2`.`titre_filiere`), '') /* Competence cible */" => "competence_principale",
		"IF(    CHAR_LENGTH(`competences_ref1`.`titre_competence`) || CHAR_LENGTH(`domaine1`.`titre_domaine`) || CHAR_LENGTH(`filiere1`.`titre_filiere`), CONCAT_WS('',   `competences_ref1`.`titre_competence`, ' ', `domaine1`.`titre_domaine`, '>', `filiere1`.`titre_filiere`), '') /* Competence secondaire */" => "competence_secondaire",
		"`formation_suivi`.`evaluation`" => "evaluation",
		"IF(    CHAR_LENGTH(`consultant1`.`Prenom`) || CHAR_LENGTH(`consultant1`.`Nom`), CONCAT_WS('',   `consultant1`.`Prenom`, ' ', `consultant1`.`Nom`), '') /* Consultant id */" => "consultant_id",
		"`formation_suivi`.`organisme`" => "organisme",
		"`formation_suivi`.`commentaire`" => "commentaire"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`formation_suivi`.`id`',
		2 => 2,
		3 => 3,
		4 => '`formation_suivi`.`date_deb`',
		5 => '`formation_suivi`.`date_fin`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`formation_suivi`.`id`" => "id",
		"`formation_suivi`.`titre`" => "titre",
		"`formation_suivi`.`niveau`" => "niveau",
		"if(`formation_suivi`.`date_deb`,date_format(`formation_suivi`.`date_deb`,'%d/%m/%Y'),'')" => "date_deb",
		"if(`formation_suivi`.`date_fin`,date_format(`formation_suivi`.`date_fin`,'%d/%m/%Y'),'')" => "date_fin",
		"IF(    CHAR_LENGTH(`competences_ref1`.`titre_competence`) || CHAR_LENGTH(`domaine2`.`titre_domaine`) || CHAR_LENGTH(`filiere2`.`titre_filiere`), CONCAT_WS('',   `competences_ref1`.`titre_competence`, ' ', `domaine2`.`titre_domaine`, '>', `filiere2`.`titre_filiere`), '') /* Competence cible */" => "competence_principale",
		"IF(    CHAR_LENGTH(`competences_ref1`.`titre_competence`) || CHAR_LENGTH(`domaine1`.`titre_domaine`) || CHAR_LENGTH(`filiere1`.`titre_filiere`), CONCAT_WS('',   `competences_ref1`.`titre_competence`, ' ', `domaine1`.`titre_domaine`, '>', `filiere1`.`titre_filiere`), '') /* Competence secondaire */" => "competence_secondaire",
		"`formation_suivi`.`evaluation`" => "evaluation",
		"IF(    CHAR_LENGTH(`consultant1`.`Prenom`) || CHAR_LENGTH(`consultant1`.`Nom`), CONCAT_WS('',   `consultant1`.`Prenom`, ' ', `consultant1`.`Nom`), '') /* Consultant id */" => "consultant_id",
		"`formation_suivi`.`organisme`" => "organisme",
		"`formation_suivi`.`commentaire`" => "commentaire"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`formation_suivi`.`id`" => "ID Formation suivie",
		"`formation_suivi`.`titre`" => "Titre de la formation",
		"`formation_suivi`.`niveau`" => "Niveau",
		"`formation_suivi`.`date_deb`" => "Date debut de la formation",
		"`formation_suivi`.`date_fin`" => "Date fin de la formation",
		"IF(    CHAR_LENGTH(`competences_ref1`.`titre_competence`) || CHAR_LENGTH(`domaine2`.`titre_domaine`) || CHAR_LENGTH(`filiere2`.`titre_filiere`), CONCAT_WS('',   `competences_ref1`.`titre_competence`, ' ', `domaine2`.`titre_domaine`, '>', `filiere2`.`titre_filiere`), '') /* Competence cible */" => "Competence cible",
		"IF(    CHAR_LENGTH(`competences_ref1`.`titre_competence`) || CHAR_LENGTH(`domaine1`.`titre_domaine`) || CHAR_LENGTH(`filiere1`.`titre_filiere`), CONCAT_WS('',   `competences_ref1`.`titre_competence`, ' ', `domaine1`.`titre_domaine`, '>', `filiere1`.`titre_filiere`), '') /* Competence secondaire */" => "Competence secondaire",
		"`formation_suivi`.`evaluation`" => "Evaluation",
		"IF(    CHAR_LENGTH(`consultant1`.`Prenom`) || CHAR_LENGTH(`consultant1`.`Nom`), CONCAT_WS('',   `consultant1`.`Prenom`, ' ', `consultant1`.`Nom`), '') /* Consultant id */" => "Consultant id",
		"`formation_suivi`.`organisme`" => "Organisme",
		"`formation_suivi`.`commentaire`" => "Commentaire"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`formation_suivi`.`id`" => "id",
		"`formation_suivi`.`titre`" => "titre",
		"`formation_suivi`.`niveau`" => "niveau",
		"if(`formation_suivi`.`date_deb`,date_format(`formation_suivi`.`date_deb`,'%d/%m/%Y'),'')" => "date_deb",
		"if(`formation_suivi`.`date_fin`,date_format(`formation_suivi`.`date_fin`,'%d/%m/%Y'),'')" => "date_fin",
		"IF(    CHAR_LENGTH(`competences_ref1`.`titre_competence`) || CHAR_LENGTH(`domaine2`.`titre_domaine`) || CHAR_LENGTH(`filiere2`.`titre_filiere`), CONCAT_WS('',   `competences_ref1`.`titre_competence`, ' ', `domaine2`.`titre_domaine`, '>', `filiere2`.`titre_filiere`), '') /* Competence cible */" => "competence_principale",
		"IF(    CHAR_LENGTH(`competences_ref1`.`titre_competence`) || CHAR_LENGTH(`domaine1`.`titre_domaine`) || CHAR_LENGTH(`filiere1`.`titre_filiere`), CONCAT_WS('',   `competences_ref1`.`titre_competence`, ' ', `domaine1`.`titre_domaine`, '>', `filiere1`.`titre_filiere`), '') /* Competence secondaire */" => "competence_secondaire",
		"`formation_suivi`.`evaluation`" => "evaluation",
		"IF(    CHAR_LENGTH(`consultant1`.`Prenom`) || CHAR_LENGTH(`consultant1`.`Nom`), CONCAT_WS('',   `consultant1`.`Prenom`, ' ', `consultant1`.`Nom`), '') /* Consultant id */" => "consultant_id",
		"`formation_suivi`.`organisme`" => "organisme",
		"`formation_suivi`.`commentaire`" => "commentaire"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'competence_secondaire' => 'Competence secondaire', 'consultant_id' => 'Consultant id');

	$x->QueryFrom = "`formation_suivi` LEFT JOIN `competences_ref` as competences_ref1 ON `competences_ref1`.`id_competence`=`formation_suivi`.`competence_secondaire` LEFT JOIN `domaine` as domaine1 ON `domaine1`.`id_domaine`=`competences_ref1`.`domaine_principal` LEFT JOIN `filiere` as filiere1 ON `filiere1`.`id_filiere`=`domaine1`.`rattache_a_filiere` LEFT JOIN `consultant` as consultant1 ON `consultant1`.`id_consultant`=`formation_suivi`.`consultant_id` LEFT JOIN `domaine` as domaine2 ON `domaine2`.`id_domaine`=`competences_ref1`.`domaine_principal` LEFT JOIN `filiere` as filiere2 ON `filiere2`.`id_filiere`=`domaine2`.`rattache_a_filiere` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "formation_suivi_view.php";
	$x->RedirectAfterInsert = "formation_suivi_view.php?SelectedID=#ID#";
	$x->TableTitle = "Formations suivis";
	$x->TableIcon = "resources/table_icons/books.png";
	$x->PrimaryKey = "`formation_suivi`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Titre de la formation", "Niveau", "Date debut de la formation", "Date fin de la formation", "Competence cible", "Competence secondaire", "Evaluation", "Consultant id", "Organisme", "Commentaire");
	$x->ColFieldName = array('titre', 'niveau', 'date_deb', 'date_fin', 'competence_principale', 'competence_secondaire', 'evaluation', 'consultant_id', 'organisme', 'commentaire');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11);

	// template paths below are based on the app main directory
	$x->Template = 'templates/formation_suivi_templateTV.html';
	$x->SelectedTemplate = 'templates/formation_suivi_templateTVS.html';
	$x->TemplateDV = 'templates/formation_suivi_templateDV.html';
	$x->TemplateDVP = 'templates/formation_suivi_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `formation_suivi`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='formation_suivi' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `formation_suivi`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='formation_suivi' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`formation_suivi`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: formation_suivi_init
	$render=TRUE;
	if(function_exists('formation_suivi_init')){
		$args=array();
		$render=formation_suivi_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: formation_suivi_header
	$headerCode='';
	if(function_exists('formation_suivi_header')){
		$args=array();
		$headerCode=formation_suivi_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: formation_suivi_footer
	$footerCode='';
	if(function_exists('formation_suivi_footer')){
		$args=array();
		$footerCode=formation_suivi_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>