<?php

// Data functions (insert, update, delete, form) for table formation_suivi

// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

function formation_suivi_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('formation_suivi');
	if(!$arrPerm[1]){
		return false;
	}

	$data['titre'] = makeSafe($_REQUEST['titre']);
		if($data['titre'] == empty_lookup_value){ $data['titre'] = ''; }
	$data['niveau'] = makeSafe($_REQUEST['niveau']);
		if($data['niveau'] == empty_lookup_value){ $data['niveau'] = ''; }
	$data['date_deb'] = intval($_REQUEST['date_debYear']) . '-' . intval($_REQUEST['date_debMonth']) . '-' . intval($_REQUEST['date_debDay']);
	$data['date_deb'] = parseMySQLDate($data['date_deb'], '');
	$data['date_fin'] = intval($_REQUEST['date_finYear']) . '-' . intval($_REQUEST['date_finMonth']) . '-' . intval($_REQUEST['date_finDay']);
	$data['date_fin'] = parseMySQLDate($data['date_fin'], '');
	$data['competence_principale'] = makeSafe($_REQUEST['competence_secondaire']);
		if($data['competence_principale'] == empty_lookup_value){ $data['competence_principale'] = ''; }
	$data['competence_secondaire'] = makeSafe($_REQUEST['competence_secondaire']);
		if($data['competence_secondaire'] == empty_lookup_value){ $data['competence_secondaire'] = ''; }
	$data['evaluation'] = makeSafe($_REQUEST['evaluation']);
		if($data['evaluation'] == empty_lookup_value){ $data['evaluation'] = ''; }
	$data['consultant_id'] = makeSafe($_REQUEST['consultant_id']);
		if($data['consultant_id'] == empty_lookup_value){ $data['consultant_id'] = ''; }
	$data['organisme'] = makeSafe($_REQUEST['organisme']);
		if($data['organisme'] == empty_lookup_value){ $data['organisme'] = ''; }
	$data['commentaire'] = makeSafe($_REQUEST['commentaire']);
		if($data['commentaire'] == empty_lookup_value){ $data['commentaire'] = ''; }

	// hook: formation_suivi_before_insert
	if(function_exists('formation_suivi_before_insert')){
		$args=array();
		if(!formation_suivi_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `formation_suivi` set       `titre`=' . (($data['titre'] !== '' && $data['titre'] !== NULL) ? "'{$data['titre']}'" : 'NULL') . ', `niveau`=' . (($data['niveau'] !== '' && $data['niveau'] !== NULL) ? "'{$data['niveau']}'" : 'NULL') . ', `date_deb`=' . (($data['date_deb'] !== '' && $data['date_deb'] !== NULL) ? "'{$data['date_deb']}'" : 'NULL') . ', `date_fin`=' . (($data['date_fin'] !== '' && $data['date_fin'] !== NULL) ? "'{$data['date_fin']}'" : 'NULL') . ', `competence_principale`=' . (($data['competence_principale'] !== '' && $data['competence_principale'] !== NULL) ? "'{$data['competence_principale']}'" : 'NULL') . ', `competence_secondaire`=' . (($data['competence_secondaire'] !== '' && $data['competence_secondaire'] !== NULL) ? "'{$data['competence_secondaire']}'" : 'NULL') . ', `evaluation`=' . (($data['evaluation'] !== '' && $data['evaluation'] !== NULL) ? "'{$data['evaluation']}'" : 'NULL') . ', `consultant_id`=' . (($data['consultant_id'] !== '' && $data['consultant_id'] !== NULL) ? "'{$data['consultant_id']}'" : 'NULL') . ', `organisme`=' . (($data['organisme'] !== '' && $data['organisme'] !== NULL) ? "'{$data['organisme']}'" : 'NULL') . ', `commentaire`=' . (($data['commentaire'] !== '' && $data['commentaire'] !== NULL) ? "'{$data['commentaire']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"formation_suivi_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: formation_suivi_after_insert
	if(function_exists('formation_suivi_after_insert')){
		$res = sql("select * from `formation_suivi` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!formation_suivi_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('formation_suivi', $recID, getLoggedMemberID());

	return $recID;
}

function formation_suivi_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('formation_suivi');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='formation_suivi' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='formation_suivi' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: formation_suivi_before_delete
	if(function_exists('formation_suivi_before_delete')){
		$args=array();
		if(!formation_suivi_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `formation_suivi` where `id`='$selected_id'", $eo);

	// hook: formation_suivi_after_delete
	if(function_exists('formation_suivi_after_delete')){
		$args=array();
		formation_suivi_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='formation_suivi' and pkValue='$selected_id'", $eo);
}

function formation_suivi_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('formation_suivi');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='formation_suivi' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='formation_suivi' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['titre'] = makeSafe($_REQUEST['titre']);
		if($data['titre'] == empty_lookup_value){ $data['titre'] = ''; }
	$data['niveau'] = makeSafe($_REQUEST['niveau']);
		if($data['niveau'] == empty_lookup_value){ $data['niveau'] = ''; }
	$data['date_deb'] = intval($_REQUEST['date_debYear']) . '-' . intval($_REQUEST['date_debMonth']) . '-' . intval($_REQUEST['date_debDay']);
	$data['date_deb'] = parseMySQLDate($data['date_deb'], '');
	$data['date_fin'] = intval($_REQUEST['date_finYear']) . '-' . intval($_REQUEST['date_finMonth']) . '-' . intval($_REQUEST['date_finDay']);
	$data['date_fin'] = parseMySQLDate($data['date_fin'], '');
	$data['competence_principale'] = makeSafe($_REQUEST['competence_secondaire']);
		if($data['competence_principale'] == empty_lookup_value){ $data['competence_principale'] = ''; }
	$data['competence_secondaire'] = makeSafe($_REQUEST['competence_secondaire']);
		if($data['competence_secondaire'] == empty_lookup_value){ $data['competence_secondaire'] = ''; }
	$data['evaluation'] = makeSafe($_REQUEST['evaluation']);
		if($data['evaluation'] == empty_lookup_value){ $data['evaluation'] = ''; }
	$data['consultant_id'] = makeSafe($_REQUEST['consultant_id']);
		if($data['consultant_id'] == empty_lookup_value){ $data['consultant_id'] = ''; }
	$data['organisme'] = makeSafe($_REQUEST['organisme']);
		if($data['organisme'] == empty_lookup_value){ $data['organisme'] = ''; }
	$data['commentaire'] = makeSafe($_REQUEST['commentaire']);
		if($data['commentaire'] == empty_lookup_value){ $data['commentaire'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: formation_suivi_before_update
	if(function_exists('formation_suivi_before_update')){
		$args=array();
		if(!formation_suivi_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `formation_suivi` set       `titre`=' . (($data['titre'] !== '' && $data['titre'] !== NULL) ? "'{$data['titre']}'" : 'NULL') . ', `niveau`=' . (($data['niveau'] !== '' && $data['niveau'] !== NULL) ? "'{$data['niveau']}'" : 'NULL') . ', `date_deb`=' . (($data['date_deb'] !== '' && $data['date_deb'] !== NULL) ? "'{$data['date_deb']}'" : 'NULL') . ', `date_fin`=' . (($data['date_fin'] !== '' && $data['date_fin'] !== NULL) ? "'{$data['date_fin']}'" : 'NULL') . ', `competence_principale`=' . (($data['competence_principale'] !== '' && $data['competence_principale'] !== NULL) ? "'{$data['competence_principale']}'" : 'NULL') . ', `competence_secondaire`=' . (($data['competence_secondaire'] !== '' && $data['competence_secondaire'] !== NULL) ? "'{$data['competence_secondaire']}'" : 'NULL') . ', `evaluation`=' . (($data['evaluation'] !== '' && $data['evaluation'] !== NULL) ? "'{$data['evaluation']}'" : 'NULL') . ', `consultant_id`=' . (($data['consultant_id'] !== '' && $data['consultant_id'] !== NULL) ? "'{$data['consultant_id']}'" : 'NULL') . ', `organisme`=' . (($data['organisme'] !== '' && $data['organisme'] !== NULL) ? "'{$data['organisme']}'" : 'NULL') . ', `commentaire`=' . (($data['commentaire'] !== '' && $data['commentaire'] !== NULL) ? "'{$data['commentaire']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="formation_suivi_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: formation_suivi_after_update
	if(function_exists('formation_suivi_after_update')){
		$res = sql("SELECT * FROM `formation_suivi` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!formation_suivi_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='formation_suivi' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function formation_suivi_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('formation_suivi');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_competence_secondaire = thisOr(undo_magic_quotes($_REQUEST['filterer_competence_secondaire']), '');
	$filterer_consultant_id = thisOr(undo_magic_quotes($_REQUEST['filterer_consultant_id']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: date_deb
	$combo_date_deb = new DateCombo;
	$combo_date_deb->DateFormat = "dmy";
	$combo_date_deb->MinYear = 1900;
	$combo_date_deb->MaxYear = 2100;
	$combo_date_deb->DefaultDate = parseMySQLDate('', '');
	$combo_date_deb->MonthNames = $Translation['month names'];
	$combo_date_deb->NamePrefix = 'date_deb';
	// combobox: date_fin
	$combo_date_fin = new DateCombo;
	$combo_date_fin->DateFormat = "dmy";
	$combo_date_fin->MinYear = 1900;
	$combo_date_fin->MaxYear = 2100;
	$combo_date_fin->DefaultDate = parseMySQLDate('', '');
	$combo_date_fin->MonthNames = $Translation['month names'];
	$combo_date_fin->NamePrefix = 'date_fin';
	// combobox: competence_secondaire
	$combo_competence_secondaire = new DataCombo;
	// combobox: consultant_id
	$combo_consultant_id = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='formation_suivi' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='formation_suivi' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `formation_suivi` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'formation_suivi_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_date_deb->DefaultDate = $row['date_deb'];
		$combo_date_fin->DefaultDate = $row['date_fin'];
		$combo_competence_secondaire->SelectedData = $row['competence_secondaire'];
		$combo_consultant_id->SelectedData = $row['consultant_id'];
	}else{
		$combo_competence_secondaire->SelectedData = $filterer_competence_secondaire;
		$combo_consultant_id->SelectedData = $filterer_consultant_id;
	}
	$combo_competence_secondaire->HTML = '<span id="competence_secondaire-container' . $rnd1 . '"></span><input type="hidden" name="competence_secondaire" id="competence_secondaire' . $rnd1 . '" value="' . html_attr($combo_competence_secondaire->SelectedData) . '">';
	$combo_competence_secondaire->MatchText = '<span id="competence_secondaire-container-readonly' . $rnd1 . '"></span><input type="hidden" name="competence_secondaire" id="competence_secondaire' . $rnd1 . '" value="' . html_attr($combo_competence_secondaire->SelectedData) . '">';
	$combo_consultant_id->HTML = '<span id="consultant_id-container' . $rnd1 . '"></span><input type="hidden" name="consultant_id" id="consultant_id' . $rnd1 . '" value="' . html_attr($combo_consultant_id->SelectedData) . '">';
	$combo_consultant_id->MatchText = '<span id="consultant_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="consultant_id" id="consultant_id' . $rnd1 . '" value="' . html_attr($combo_consultant_id->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_competence_secondaire__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['competence_secondaire'] : $filterer_competence_secondaire); ?>"};
		AppGini.current_consultant_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['consultant_id'] : $filterer_consultant_id); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(competence_secondaire_reload__RAND__) == 'function') competence_secondaire_reload__RAND__();
				if(typeof(consultant_id_reload__RAND__) == 'function') consultant_id_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function competence_secondaire_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#competence_secondaire-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_competence_secondaire__RAND__.value, t: 'formation_suivi', f: 'competence_secondaire' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="competence_secondaire"]').val(resp.results[0].id);
							$j('[id=competence_secondaire-container-readonly__RAND__]').html('<span id="competence_secondaire-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=competences_ref_view_parent]').hide(); }else{ $j('.btn[id=competences_ref_view_parent]').show(); }


							if(typeof(competence_secondaire_update_autofills__RAND__) == 'function') competence_secondaire_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'formation_suivi', f: 'competence_secondaire' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_competence_secondaire__RAND__.value = e.added.id;
				AppGini.current_competence_secondaire__RAND__.text = e.added.text;
				$j('[name="competence_secondaire"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=competences_ref_view_parent]').hide(); }else{ $j('.btn[id=competences_ref_view_parent]').show(); }


				if(typeof(competence_secondaire_update_autofills__RAND__) == 'function') competence_secondaire_update_autofills__RAND__();
			});

			if(!$j("#competence_secondaire-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_competence_secondaire__RAND__.value, t: 'formation_suivi', f: 'competence_secondaire' },
					success: function(resp){
						$j('[name="competence_secondaire"]').val(resp.results[0].id);
						$j('[id=competence_secondaire-container-readonly__RAND__]').html('<span id="competence_secondaire-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=competences_ref_view_parent]').hide(); }else{ $j('.btn[id=competences_ref_view_parent]').show(); }

						if(typeof(competence_secondaire_update_autofills__RAND__) == 'function') competence_secondaire_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_competence_secondaire__RAND__.value, t: 'formation_suivi', f: 'competence_secondaire' },
				success: function(resp){
					$j('[id=competence_secondaire-container__RAND__], [id=competence_secondaire-container-readonly__RAND__]').html('<span id="competence_secondaire-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=competences_ref_view_parent]').hide(); }else{ $j('.btn[id=competences_ref_view_parent]').show(); }

					if(typeof(competence_secondaire_update_autofills__RAND__) == 'function') competence_secondaire_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function consultant_id_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#consultant_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_consultant_id__RAND__.value, t: 'formation_suivi', f: 'consultant_id' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="consultant_id"]').val(resp.results[0].id);
							$j('[id=consultant_id-container-readonly__RAND__]').html('<span id="consultant_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=consultant_view_parent]').hide(); }else{ $j('.btn[id=consultant_view_parent]').show(); }


							if(typeof(consultant_id_update_autofills__RAND__) == 'function') consultant_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'formation_suivi', f: 'consultant_id' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_consultant_id__RAND__.value = e.added.id;
				AppGini.current_consultant_id__RAND__.text = e.added.text;
				$j('[name="consultant_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=consultant_view_parent]').hide(); }else{ $j('.btn[id=consultant_view_parent]').show(); }


				if(typeof(consultant_id_update_autofills__RAND__) == 'function') consultant_id_update_autofills__RAND__();
			});

			if(!$j("#consultant_id-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_consultant_id__RAND__.value, t: 'formation_suivi', f: 'consultant_id' },
					success: function(resp){
						$j('[name="consultant_id"]').val(resp.results[0].id);
						$j('[id=consultant_id-container-readonly__RAND__]').html('<span id="consultant_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=consultant_view_parent]').hide(); }else{ $j('.btn[id=consultant_view_parent]').show(); }

						if(typeof(consultant_id_update_autofills__RAND__) == 'function') consultant_id_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_consultant_id__RAND__.value, t: 'formation_suivi', f: 'consultant_id' },
				success: function(resp){
					$j('[id=consultant_id-container__RAND__], [id=consultant_id-container-readonly__RAND__]').html('<span id="consultant_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=consultant_view_parent]').hide(); }else{ $j('.btn[id=consultant_view_parent]').show(); }

					if(typeof(consultant_id_update_autofills__RAND__) == 'function') consultant_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/formation_suivi_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/formation_suivi_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Formation suivi details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return formation_suivi_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return formation_suivi_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return formation_suivi_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#titre').replaceWith('<div class=\"form-control-static\" id=\"titre\">' + (jQuery('#titre').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#niveau').replaceWith('<div class=\"form-control-static\" id=\"niveau\">' + (jQuery('#niveau').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#date_deb').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#date_debDay, #date_debMonth, #date_debYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#date_fin').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#date_finDay, #date_finMonth, #date_finYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#competence_secondaire').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#competence_secondaire_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#evaluation').replaceWith('<div class=\"form-control-static\" id=\"evaluation\">' + (jQuery('#evaluation').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#consultant_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#consultant_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#organisme').replaceWith('<div class=\"form-control-static\" id=\"organisme\">' + (jQuery('#organisme').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(date_deb)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_date_deb->GetHTML(true) . '</div>' : $combo_date_deb->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date_deb)%%>', $combo_date_deb->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(date_fin)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_date_fin->GetHTML(true) . '</div>' : $combo_date_fin->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date_fin)%%>', $combo_date_fin->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(competence_secondaire)%%>', $combo_competence_secondaire->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(competence_secondaire)%%>', $combo_competence_secondaire->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(competence_secondaire)%%>', urlencode($combo_competence_secondaire->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(consultant_id)%%>', $combo_consultant_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(consultant_id)%%>', $combo_consultant_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(consultant_id)%%>', urlencode($combo_consultant_id->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'competence_secondaire' => array('competences_ref', 'Competence secondaire'), 'consultant_id' => array('consultant', 'Consultant id'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(titre)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(niveau)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date_deb)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date_fin)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(competence_secondaire)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(evaluation)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(consultant_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(organisme)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(commentaire)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(titre)%%>', safe_html($urow['titre']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(titre)%%>', html_attr($row['titre']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(titre)%%>', urlencode($urow['titre']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(niveau)%%>', safe_html($urow['niveau']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(niveau)%%>', html_attr($row['niveau']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(niveau)%%>', urlencode($urow['niveau']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_deb)%%>', @date('d/m/Y', @strtotime(html_attr($row['date_deb']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_deb)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['date_deb'])))), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_fin)%%>', @date('d/m/Y', @strtotime(html_attr($row['date_fin']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_fin)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['date_fin'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(competence_secondaire)%%>', safe_html($urow['competence_secondaire']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(competence_secondaire)%%>', html_attr($row['competence_secondaire']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(competence_secondaire)%%>', urlencode($urow['competence_secondaire']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(evaluation)%%>', safe_html($urow['evaluation']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(evaluation)%%>', html_attr($row['evaluation']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(evaluation)%%>', urlencode($urow['evaluation']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(consultant_id)%%>', safe_html($urow['consultant_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(consultant_id)%%>', html_attr($row['consultant_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(consultant_id)%%>', urlencode($urow['consultant_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(organisme)%%>', safe_html($urow['organisme']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(organisme)%%>', html_attr($row['organisme']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(organisme)%%>', urlencode($urow['organisme']), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode = str_replace('<%%HTMLAREA(commentaire)%%>', '<textarea name="commentaire" id="commentaire" rows="5">' . html_attr($row['commentaire']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(commentaire)%%>', '<div id="commentaire" class="form-control-static">' . $row['commentaire'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(commentaire)%%>', nl2br($row['commentaire']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(commentaire)%%>', urlencode($urow['commentaire']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(titre)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(titre)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(niveau)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(niveau)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_deb)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_deb)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_fin)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_fin)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(competence_secondaire)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(competence_secondaire)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(evaluation)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(evaluation)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(consultant_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(consultant_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(organisme)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(organisme)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(commentaire)%%>', '<textarea name="commentaire" id="commentaire" rows="5"></textarea>', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tcompetence_secondaire_update_autofills$rnd1 = function(){\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'formation_suivi_autofill.php?rnd1=$rnd1&mfk=competence_secondaire&id=' + encodeURIComponent('".addslashes($row['competence_secondaire'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'formation_suivi_autofill.php?rnd1=$rnd1&mfk=competence_secondaire&id=' + encodeURIComponent(AppGini.current_competence_secondaire{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#competence_secondaire$rnd1').prop('disabled', true); \$j('#competence_secondaireLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#competence_secondaire$rnd1').prop('disabled', false); " : "\$j('#competence_secondaire$rnd1').prop('disabled', true); ")."\$j('#competence_secondaireLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#competence_secondaire_caption').length) \$j('#competence_secondaire_caption').click(function(){ /* */ competence_secondaire_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('formation_suivi');
	if($selected_id){
		$jdata = get_joined_record('formation_suivi', $selected_id);
		if($jdata === false) $jdata = get_defaults('formation_suivi');
		$rdata = $row;
	}
	$templateCode .= loadView('formation_suivi-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: formation_suivi_dv
	if(function_exists('formation_suivi_dv')){
		$args=array();
		formation_suivi_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>